name: w3c_event_source
version: 2.0.0
description: W3C EventSource client implementation for Dart / Flutter,
  to communicate with server-sent event endpoints.
author: Renée Kooi <renee@kooi.me>
homepage: https://github.com/goto-bus-stop/dart-event-source

environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  test: ^1.16.8
